[package]
name = "bagua-exchange"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
bagua-types = { workspace = true }
bagua-helpers = { workspace = true }